### ISSUE TITLE
Problema con método Bind en RegisterController

### ISSUE THREAD

**Issue by jekferson** [Tecnocreaciones/AjaxFOSUserBundle#12]
Buenas Noches, estoy usando el Bundle AjaxFOSUserBundle con FOSUserBundle 2.0 y Symfony 3.3.8 y al enviar con ajax el formulario de Registro de usuario me da el siguiente error.

Attempted to call an undefined method named "bind" of class "Symfony\Component\Form\Form".

Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "bind" of class "Symfony\Component\Form\Form"." at /opt/lampp/htdocs/yeshiva-online/vendor/tecnocreaciones/ajax-fos-user-bundle/Tecnocreaciones/Bundle/AjaxFOSUserBundle/Controller/RegistrationController.php line 98

Por lo cual no me permite guardar el registro devolviendome un estatus 500, estuve leyendo y el problema es que el método bind fue deprecado en dicha versión de symfony.

**Comment by INHack20** [comment]
Gracias ya realice el merge que enviaste.
