### ISSUE TITLE
Problema con la versión 1.x

### ISSUE THREAD

**Issue by jekferson** [Tecnocreaciones/AjaxFOSUserBundle#14]
Buenas Tardes amigos, tengo problemas para instalar la versión 1.x a través de composer, alguna idea para poder solventarlo ? tengo actualmente instalada la versión master

**Comment by INHack20** [comment]
Amigo buenas tardes, actualmente me encuentro un poco ocupado pero te he agregado como contribuidor, por favor solventa las dependencias, me imagino que con symfony3 te esta dando problemas, le dejas compatibilidad con symfony2.

Gracias, espero puedas colaborar.

**Comment by jekferson** [comment]
En este caso no es mejor que se cree una versión de tu bundle que sea dedicado solo a la versión 3+ de symfony, ya que hay métodos deprecados en dicha versión ??
